on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-15
    env:
      GABBER_CI: "true"
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup build tools
        run: |
          brew install just
          sudo xcode-select --switch /Applications/Xcode_16.3.app
      - name: Build apps
        run: just build Release

  format:
    runs-on: macos-15
    env:
      GABBER_CI: "true"
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: package.json
      - name: Setup build tools
        run: |
          brew install just
          sudo xcode-select --switch /Applications/Xcode_16.3.app
      - name: Setup npm dependencies
        run: |
          npm ci
      - name: Check formatting
        run: just check-format

  lint:
    runs-on: macos-15
    env:
      GABBER_CI: "true"
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: package.json
      - name: Setup build tools
        run: |
          brew install just
          sudo xcode-select --switch /Applications/Xcode_16.3.app
      - name: Setup npm dependencies
        run: |
          npm ci
      - name: Check linting
        run: just check-lint

  test:
    runs-on: macos-15
    env:
      GABBER_CI: "true"
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: package.json
      - name: Setup build tools
        run: |
          brew install just
      - name: Setup npm dependencies
        run: |
          npm ci
      - name: Test extension
        run: just test-extension
