on:
  pull_request: {}
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-15
    env:
      GABBER_CI: "true"
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Setup build tools
        run: |
          brew install just
          sudo xcode-select --switch /Applications/Xcode_16.3.app
      - name: Build apps
        run: just build Release

  format:
    runs-on: macos-15
    env:
      GABBER_CI: "true"
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version-file: package.json
      - name: Setup build tools
        run: |
          brew install just
          sudo xcode-select --switch /Applications/Xcode_16.3.app
      - name: Setup npm dependencies
        run: |
          npm ci
      - name: Check formatting
        run: just check-format

  lint:
    runs-on: macos-15
    env:
      GABBER_CI: "true"
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version-file: package.json
      - name: Setup build tools
        run: |
          brew install just
          sudo xcode-select --switch /Applications/Xcode_16.3.app
      - name: Setup npm dependencies
        run: |
          npm ci
      - name: Check linting
        run: just check-lint

  test:
    runs-on: macos-15
    env:
      GABBER_CI: "true"
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version-file: package.json
      - name: Setup build tools
        run: |
          brew install just
      - name: Setup npm dependencies
        run: |
          npm ci
      - name: Test extension
        run: just test-extension
